# flake8: noqa

"""
    CloudOS Compute API

    CloudOS Compute API for batch style workloads in Autodesk. Developers can register compute worker types by following the cloudOS2.0 onboarding process. Users can submit jobs against registered worker types. The system treats input and output as opaque JSON payloads that must confirm to the JSON schema specified by the worker documentation outside this system. All APIs are used with the /api/v1 prefix.   # noqa: E501

    The version of the OpenAPI document: 1.0.18
    Contact: cloudos-compute@autodesk.com
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from jmclient.api_client import ApiClient

# import Configuration
from jmclient.configuration import Configuration

# import exceptions
from jmclient.exceptions import OpenApiException
from jmclient.exceptions import ApiAttributeError
from jmclient.exceptions import ApiTypeError
from jmclient.exceptions import ApiValueError
from jmclient.exceptions import ApiKeyError
from jmclient.exceptions import ApiException
