package com.autodesk.compute.model.cosv2;

/**
 * Created by t_gomesa on 2017-05-12.
 */
public enum ApiOperationType {
    GET_APPLICATIONS,
    READ_APPLICATION,
    CREATE_OR_UPDATE_APPLICATION,
    DELETE_APPLICATION,
    ONBOARD_APPLICATION,
    PURGE_APPLICATION,
    CREATE_OR_UPDATE_CERT,
    DELETE_CERT,
    GET_CERT,
    GET_DASHBOARD,
    CREATE_OR_UPDATE_DASHBOARD,
    CREATE_OR_UPDATE_DNS,
    DELETE_DNS,
    DELETE_APP_DEPLOYMENT_RECORD,
    GET_APPCONFIG_POLICY,
    CREATE_APPCONFIG_POLICY,
    UPDATE_APPCONFIG_POLICY,
    SYNC_APPCONFIG_POLICY
}
