schema: v2
service: fpccomp
project: forge-cd-services
pipelines:
  completionLambda:
    type: lambda
  testJobsLambda:
    type: lambda
  cleanupLambda:
    type: lambda
deploy:
  envs:
    - name: dev
      regions:
        - region: us-west-2
    - name: stg
      regions:
        - region: us-east-1
        - region: eu-west-1
    - name: stg-fedramp
      regions:
        - region: us-east-2
    - name: prd
      regions:
        - region: us-east-1
        - region: eu-west-1
        - region: ap-southeast-2
          validationRegion:
            region: us-east-1
    - name: prd-fedramp
      regions:
        - region: us-east-2
